### ISSUE TITLE
Missing _imagingft C module in Pillow python package

### ISSUE THREAD

**Issue by tbaptista** [bitnami/bitnami-docker-odoo#104]
**Description**

On a newly deployed Odoo 14 instance, there are errors in the log when there is an attempt from the web_editor to render a font to image. The underlying python module to do it is Pillow that seems to not be installed correctly as an underlying C library is not installed. The C library is _imagingft.

Tried several versions of the Helm chart and docker image tag, but issue maintains. Reporting on the latest version.

**Steps to reproduce the issue:**

1. Install Odoo from helm chart (using latest version 19.0.4 and image tag 14.0.20210710-debian-10-r26)
2. Call https://your-domain/web_editor/font_to_img/61682/rgb(33,37,41)/14
3. Check the logs

**Describe the results you received:**

The request returns: 

> Internal Server Error
> 
> The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
> 

The logs have an exception:
> ImportError: The _imagingft C module is not installed

**Describe the results you expected:**

The image should be rendered and returned.

**Additional information you deem important (e.g. issue happens only occasionally):**

Can resolve the issue by reinstalling the Pillow module in the Odoo venv:

`/opt/bitnami/odoo/venv/bin/pip install --force-reinstall Pillow==8.1.1`

After a restart of the service, everything works correctly.

**Comment by migruiz4** [comment]
Hi @tbaptista,

I'm sorry but looks like my attempt to fix this issue is not working as expected. 

We pack Odoo and Python + dependencies with the help of virtualenv. I initially thought an additional Pillow dependency would be missing (libfreetype-dev) and adding it would fix the problem, but looks like in the process they are being stripped and the issue persists.

For instance, these is the track I followed:
Running command `/opt/bitnami/odoo/venv/bin/python` tried:
```
from PIL import ImageFont

font = ImageFont.truetype('arial.ttf', 14)
```

Got the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/bitnami/odoo/venv/lib/python3.8/site-packages/PIL/ImageFont.py", line 852, in truetype
    return freetype(font)
  File "/opt/bitnami/odoo/venv/lib/python3.8/site-packages/PIL/ImageFont.py", line 849, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/opt/bitnami/odoo/venv/lib/python3.8/site-packages/PIL/ImageFont.py", line 185, in __init__
    if core.HAVE_RAQM:
  File "/opt/bitnami/odoo/venv/lib/python3.8/site-packages/PIL/ImageFont.py", line 44, in __getattr__
    raise ImportError("The _imagingft C module is not installed")
ImportError: The _imagingft C module is not installed
```
 
Checking the error at `PIL/ImageFont.py`:
```
try:
    from . import _imagingft as core
except ImportError:
    core = _imagingft_not_installed()
```

Meaning it is an issue importing `_imagingft`. Using venv python again:
```
>>> from PIL import _imagingft
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libfreetype-6ad068c6.so.6.17.4: ELF load command address/offset not properly aligned
```

As I previously mentioned, this error would mean that although I installed libfreetype, it is being stripped in the Odoo building process which would require us more time to fix this issue.

I'm sorry for the inconveniences.

**Comment by porfirioribeiro** [comment]
I'm also having this issue with the latest Odoo 15.0
Is there any way for this to be solved?
`ImportError: The _imagingft C module is not installed - - -`

**Comment by tbaptista** [comment]
If you force re-install Pillow it should work. At least it did for the versions I tested. Check the command above, but verify what version of Pillow is compatible with your version of Odoo.

**Comment by carrodher** [comment]
Hi, unfortunately, if the issue is not solved in recent versions means the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-odoo#community-supported-solution) since this asset was marked as a “Community supported solution”.

At this point, the best option to fix any issue or add a new feature is to contribute create a PR; the Bitnami team will be happy to review it and provide feedback.
