### ISSUE TITLE
Update/init module programmatically

### ISSUE THREAD

**Issue by antonioredpipe** [bitnami/bitnami-docker-odoo#45]
I'm developing an script-based solution to update changes in a custom module instead of manually logging in Odoo and updating it.

In a non-dockerized solution it seems easy, as you can init or update modules when you launch the oddo-bin:
`odoo-bin -u mymodulename -d mydbname`    to update mymodulename
`odoo-bin -i mymodulename -d mydbname`    to init mymodulename

But using the Bitnami Odoo docker seems complicated as the Odoo python process is launched with nami and I cannot add parameters in the nami call. I could not find any other way to update or init a module programmatically so now I'm stucked. 

Anyone has any idea for this?

Thanks!

Antonio

**Comment by juan131** [comment]
Hi @antonioredpipe 

As you mentioned, [Nami](https://github.com/bitnami/nami) is the one which starts the Odoo service and it's running the command below to do so:

```
/opt/bitnami/odoo/venv/bin/python /opt/bitnami/odoo/odoo-server --config /opt/bitnami/odoo/odoo-server.conf
```

I'm not a Odoo expert but I think you could indicate what modules to update/initialise on the **odoo-server.conf** file (see https://www.odoo.com/documentation/11.0/reference/cmdline.html#configuration-file) so you could update/initialise it using the command that Nami uses. Does it make sense?

In order to modify the **odoo-server.conf** file, you could edit the [app-entrypoint.sh](https://github.com/bitnami/bitnami-docker-odoo/blob/master/11/rootfs/app-entrypoint.sh) so you append some lines to it before initialising Odoo.
