### ISSUE TITLE
Adding python modules

### ISSUE THREAD

**Issue by gridworkz** [bitnami/bitnami-docker-odoo#53]
I need to add "wkhtmltopdf" and other python/apt modules to the Bitnami Odoo image. Where in the boot process should I put the following code:

`apt-get update`
`apt-get install vim nano wget fontconfig xfonts-75dpi xfonts-base libxrender1 xvfb python-requests python-unicodecsv libxml2-dev libxmlsec1-dev python3-lasso -y` 
`wget -N http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz && gunzip GeoLiteCity.dat.gz && mkdir /usr/share/GeoIP/ && mv GeoLiteCity.dat /usr/share/GeoIP/` 
`pip3 install pyotp unidecode wand checksumdir num2words cachetools validate_email phonenumbers simplejson oauthlib pyqrcode`
`wget http://archive.ubuntu.com/ubuntu/pool/main/libj/libjpeg-turbo/libjpeg-turbo8_2.0.0-0ubuntu2_amd64.deb && dpkg -i libjpeg-turbo8_2.0.0-0ubuntu2_amd64.deb`
`wget http://archive.ubuntu.com/ubuntu/pool/main/libp/libpng/libpng12-0_1.2.54-1ubuntu1_amd64.deb && dpkg -i libpng12-0_1.2.54-1ubuntu1_amd64.deb` 
`wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.0.0_1.0.2g-1ubuntu4.14_amd64.deb && dpkg -i libssl1.0.0_1.0.2g-1ubuntu4.14_amd64.deb` 
`wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.1/wkhtmltox-0.12.1_linux-trusty-amd64.deb && dpkg -i wkhtmltox-0.12.1_linux-trusty-amd64.deb`
`cp /usr/local/bin/wkhtmltopdf /usr/bin`
`cp /usr/local/bin/wkhtmltoimage /usr/bin`

**Comment by andresbono** [comment]
Hi @gridworkz, you can add it in the [Dockerfile](https://github.com/bitnami/bitnami-docker-odoo/blob/master/11/debian-9/Dockerfile) by adding `RUN` directives. For instance, you can install the required system packages by adding:

```Dockerfile
...
RUN apt-get update && apt-get install vim nano wget ...
...
```

Note that you can use `install_packages` in the Bitnami containers instead of `apt-get update` + `apt-get install` but it's up to you. See how this is done in https://github.com/bitnami/bitnami-docker-odoo/blob/master/11/debian-9/Dockerfile#L5.

Once you have all the directives in the Dockerfile, you will need to build your customized Docker image with `docker build` and then you will be able to use it.

Let us know if you need more details on how to do it!

**Comment by gridworkz** [comment]
Ah, got it, Thanks so much. I'm just getting familiar with my dev pipeline
workflow. So, do I fork this repo and make changes then use the newly built
image from my own github fork? I'm ultimately going to use this with your
Odoo Helm chart in Rancher. Are there any other steps I need to perform to
use the new image in your Helm chart and Rancher? Cheers, Dave

**Comment by andresbono** [comment]
Hi @gridworkz, if you want to use it in Rancher, you will need to publish the Docker image so it is available there:

https://docs.docker.com/engine/reference/commandline/push/

You will need to change the reference to the image in the `values.yml` file of the chart:

https://github.com/helm/charts/blob/master/stable/odoo/values.yaml#L10-L13

Hope it helps!

**Comment by gridworkz** [comment]
Perfect, thanks...
