### ISSUE TITLE
Stuck at nami INFO Initializing odoo

### ISSUE THREAD

**Issue by mumrau** [bitnami/bitnami-docker-odoo#58]
Hello.

I'm facing an issue using odoo on kubernetes, but I highly doubt this is a kubernetes/helm related issue.
My container, despite several restarts, is completely stale after only this little set of logs: 
```

Welcome to the Bitnami odoo container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-odoo
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-odoo/issues

nami    INFO  Initializing odoo
```

Of course I updated the Readiness and Healthchecks for extended period of times to leave odoo enough time for xatabase check-ups and whatever it needs to do before being online, but nothing will happen, still perfectly wtuck at that phase.
According to the specified `app-entrypoint.sh` :
```
. /opt/bitnami/base/functions
. /opt/bitnami/base/helpers

print_welcome_page

if [[ "$1" == "nami" && "$2" == "start" ]] || [[ "$1" == "/init.sh" ]]; then
  nami_initialize odoo
  info "Starting odoo... "
fi
```
I concluded that the phase failing was `nami_initialize odoo` (I also investigated into the container itself but didn't find any lock file or anything...).

I am no professional in the whole nami framework, and I can't really diagnose this out.

I'm using the latest version of the image, namely `11.0.20190315`, and everything was working fine in terms of configuration, volumes provisionning, etc... The postgre alongside is completely healthy by the way.

Feel free to ask me anything, and thank you!

**Comment by carrodher** [comment]
You can add more debug traces using the `NAMI_DEBUG` environment variable, for example if you are using docker-compose, you can add something like:
```yaml
services:
  application:
  ...
  environment:
      - NAMI_DEBUG='--log-level=trace8'
  ...
```
or in the case of charts:
```yaml
    ...
    spec:
      containers:
      - env:
        - name: NAMI_DEBUG
          value: --log-level=trace8
      ...
```

Anyway it seems a persistence issue, it should exists a _/bitnami/odoo/.initialized_ file that indicate if the container was previously initializated or not. `nami` check this file in order to apply the configuration from scratch or use an existing one. Can you check if this file is present? Note that _/bitnami/odoo/_ is persisted

**Comment by mumrau** [comment]
Sorry for the re-opening, it is probably not here to discuss that. I faced the problem and I just need to update my healthchecks and readinesschecks delays, it needs more than 12 minutes to complete start-up and needs to not be killed beforehand of course.
It feels long kind of :package:

**Comment by carrodher** [comment]
It shouldn't take 12 minutes, I just deployed it from scratch in 3-4 minutes:
```bash
$ helm install stable/odoo --name petetoo

$ kubectl get pods | grep petetoo
petetoo-odoo-79d8866897-s7hkj                                     1/1       Running            0          4m
petetoo-postgresql-0                                              1/1       Running            0          4m
```

Is it an isolated issue or are you facing it several times?

**Comment by mumrau** [comment]
First deployment takes around 6 minutes I'd say, but then, has the quantity of data grows, the start-up times increases as well.
Nonetheless what looks disturbing to me is that there is more than 10 minutes in between the `nami    INFO  Initializing odoo`  line and the next one (and then it goes crazy recovering the data from the database, outputting many lines in a few minutes). 
I don't really get how come it is "stuck" in that phase.
I'll try and play around in between readiness and liveness probes. Maybe readiness triggers something?

**Comment by carrodher** [comment]
As mentioned above, using the `NAMI_DEBUG`, does any relevant/useful information appear?
It is weird because the first time, the container needs to do some configuration steps, like:
- Configure database
- Connect to the external db
- Import Odoo config file
- Configure login
- Configure SMTP

While the next times (due to the `.initialized`) those steps are not performed, so the following initializations should be faster. Feel free to paste here the log output (without sensitive information), at least those parts you consider important to solve the issue.
