### ISSUE TITLE
Odoo 12.0-20190515 Question: Technical Settings block missing in user settings

### ISSUE THREAD

**Issue by gridworkz** [bitnami/bitnami-docker-odoo#63]
I just did a fresh install of Odoo 12.0-20190515 on my Kubernetes cluster with the latest Bitnami Odoo Helm chart. I don't see Technical / Settings in the admin user profile until I install the eCommerce module (as superuser). Switching to developer mode didn't seem to do the trick. Has anyone experienced this? I haven't tried a plain old local install to see if it's a real bug or not.

**Comment by juan131** [comment]
Hi @gridworkz 

Do you mean that you obtain sth like this?

![Screenshot 2019-06-06 at 11 56 54](https://user-images.githubusercontent.com/6740773/59024462-3b97a300-8852-11e9-82a6-37a8d81396ad.png)

I can't confirm it but I'd say that's the expected behaviour. Did you ask on [Odoo forums](https://www.odoo.com/forum/help-1)? The might have information whether it's a bug or just the way it looks in the Odoo 12 version.

**Comment by gridworkz** [comment]
Thanks, I'll check with the Odoo folks...
Cheers,
Dave

**Comment by juan131** [comment]
Great @gridworkz 

Please let us know what you find out once they respond you!
