### ISSUE TITLE
Adding additional libraries to Dockerfile

### ISSUE THREAD

**Issue by gridworkz** [bitnami/bitnami-docker-odoo#64]
Hi Guys:

I'm trying to add some extra Python libraries to the Dockerfile: https://github.com/bitnami/bitnami-docker-odoo/blob/12.0.20190515-debian-9-r15/12/debian-9/Dockerfile

Basically I'm trying to add these Python3 libraries:

pip3 install pyotp unidecode wand checksumdir num2words cachetools validate_email phonenumbers simplejson oauthlib pyqrcode pyldap

pip3.6 install paramiko

When I build the Docker image it says it can't find /bin/sh/pip3. Is there any way to recognize pip3? Or is there another way to install python3 libs in the Dockerfile with Bitnami install tools.

D.

**Comment by alemorcuq** [comment]
Hi, @gridworkz.

When are you trying to install those libraries? Note that `pip` is not available in the `PATH` until after line 12, when it's added to the path:

```Dockerfile
ENV BITNAMI_APP_NAME="odoo" \
    BITNAMI_IMAGE_VERSION="12.0.20190515-debian-9-r15" \
    ODOO_EMAIL="user@example.com" \
    ODOO_PASSWORD="bitnami" \
    PATH="/opt/bitnami/python/bin:/opt/bitnami/postgresql/bin:/opt/bitnami/node/bin:$PATH" \
    POSTGRESQL_HOST="postgresql" \
    POSTGRESQL_PASSWORD="" \
    POSTGRESQL_PORT_NUMBER="5432" \
    POSTGRESQL_USER="postgres" \
    SMTP_HOST="" \
    SMTP_PASSWORD="" \
    SMTP_PORT="" \
    SMTP_PROTOCOL="" \
    SMTP_USER=""
```

You have two make sure you are calling `pip` after the `PATH` has been updated. Or you could run `pip` before that by specifying the full path:

```Dockerfile
RUN /opt/bitnami/python/bin/pip package-1 package-2 package-3
```

Also, all of `pip`, `pip3` and `pip3.6` inside `/opt/bitnami/python/bin` are the same, so you can just run `pip` instead of `pip3` and `pip3.6`.

Regards,
Alejandro

**Comment by gridworkz** [comment]
Ahhh, I'm an idiot....ok, it's Friday! Thanks so much....

**Comment by alemorcuq** [comment]
Nevermind! I'm closing this issue, but don't hesitate to open an issue anytime.

**Comment by gridworkz** [comment]
Hi:

Perfect, thanks...

D.
