### ISSUE TITLE
Missing wkhtmltopdf with Qt patch to generate PDF

### ISSUE THREAD

**Issue by max3903** [bitnami/bitnami-docker-odoo#79]
**Description**

I can't print any PDF document.

**Steps to reproduce the issue:**

1. Go to Accounting
2. Select or create an invoice
3. Click on Print

**Describe the results you received:**

The report shows up in HTML.

**Describe the results you expected:**

The report shows up in PDF.

**Additional information you deem important (e.g. issue happens only occasionally):**

The image is missing wkhtmltopdf

**Version**

Tested with Odoo 13. Seems to be the same with 12.

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

OpenShift 4.3 on AWS.

**Comment by andresbono** [comment]
Hi @max3903, thanks for filling this issue. As you opened a PR, let's keep the conversation there.

Thanks for your contribution!

**Comment by andresbono** [comment]
As we said in the PR, we will keep this issue opened until we add in the README some guidelines to install the extension.

**Comment by michafn** [comment]
why is this on hold? it seems an ongoing discussion and it seems pretty much useless, to have odo helmchart, but the odoo image does not contain wkhtmltopdf. I know there are several guides on how to install it in a container, but since it is not persisted i have to redo it whenever my pod restarts the container. I fail to understand the idea behind that. Why is this not included, since it is a very fundamental feature for odoo. 
Also, how do i restart the service in the odoo containeer? I have non of the ctl scripts and if i recreate a new container to get it restarted, then obviously my plugin is lost again (since not persisted). Seems the only way is to pull the odoo image, modify it and load it from our own registry, but this seems the wrong approach either, since it contradicts the idea of a central maintained repository again. Any hints/suggestions?

**Comment by andresbono** [comment]
Hi @michafn, as you mention, right now you will need to create your own image based on `bitnami/odoo` if you want to include the `wkhtmltopdf` plugin on your own custom image. The reasons behind this are explained here: https://github.com/bitnami/bitnami-docker-odoo/pull/80#issuecomment-582295402.

However, this is still on hold until we document how to do it in the README.md.

If you have suggestions on how to solve the issue differently, please let us know.

**Comment by marcosbc** [comment]
Hi @michafn @max3903, we have added wkhtmltopdf to the Bitnami Odoo container. Check out the new container revisions with the fix:

* 11.0.20200315-debian-10-r4
* 12.0.20200315-debian-10-r4
* 13.0.20200310-debian-10-r9
